### ISSUE TITLE
I am not able to install the script on Windows 

### ISSUE THREAD

**Issue by DarkHorse-APP2** [meshstyles/bash_downloaders#11] opened 2022-01-30 19:19 UTC
**When I try to build the script using this command _bash ./build.sh_ on Windows it shows the next message:**

_fi
dos2unix: Failed to change the permissions of temporary output file ./d2utmpJkWq2X: Operation not permitted
dos2unix: dos2unix: problems converting file media_dl.sh
dos2unix: Failed to change the permissions of temporary output file 0web/d2utmpK3q8O1: Operation not permitted
dos2unix: dos2unix: problems converting file 0web/media_dl_srv.sh
mkdir: cannot create directory ‘0releases’: File exists
chmod: changing permissions of 'media_dl_srv.sh': Operation not permitted
activelist
.htaccess
tar: downloads: Cannot stat: No such file or directory
index.html
media_dl_srv.sh
tar: Exiting with failure status due to previous errors_

**by the way I already installed all the dependencies except _pup_.
Any ideas please?**

**Comment by meshstyles** [comment] 2022-01-31 01:08
Hi
building the script is defo an optional step. the how to is very lacking at the moment.
The dependencies listed are for the scripts and their development and when you use it not building in itself.
the only program which usually might not come with a normal distro is `dos2unix`.

```dos2unix: Failed to change the permissions of temporary output file ./d2utmpJkWq2X: Operation not permitted
dos2unix: dos2unix: problems converting file media_dl.sh
dos2unix: Failed to change the permissions of temporary output file 0web/d2utmpK3q8O1: Operation not permitted
dos2unix: dos2unix: problems converting file 0web/media_dl_srv.sh
mkdir: cannot create directory ‘0releases’: File exists
chmod: changing permissions of 'media_dl_srv.sh': Operation not permitted
```
this looks a lot like you may not have permissions to do certain opetrations.
this might be fixed if you work in a directory you own and use the git cli under linux.
if you know what you do, you can also change the ownership of the file to the current user. this would be something like `chown $(whoami) -R *` in the project directory but this can cause issues if you use someone elses files.

`mkdir: cannot create directory ‘0releases’: File exists` this one will be fixed soon since it's irritating output but this is not really an error intiself. ther was just already a folder called 0realeases created in previous runs.

```activelist
.htaccess
tar: downloads: Cannot stat: No such file or directory
index.html
media_dl_srv.sh
tar: Exiting with failure status due to previous errors
```
this is normal output and one error which is explained in the following, this is a bug on my side.

`tar: downloads: Cannot stat: No such file or directory` this is an error i can reproduce on my side i did not include the downloads folder in the git and therefore this will fail. I'll now include a step in the script to create a folder that way i don't need to include an empty folder in the git.

**Comment by meshstyles** [comment] 2022-07-26 13:08
Does the issue still persist? if you don't respond within 2 weeks I'll close the issue.

**Comment by meshstyles** [comment] 2022-10-03 22:19
some more time has passed now and i can't help without further info. closing the issue for now

**Closed as completed by meshstyles** 2022-10-03 22:19 UTC
